/* Auto-generated by train_cmd_model.py - DO NOT EDIT */
#ifndef SPEECH_CMD_TABLE_H
#define SPEECH_CMD_TABLE_H

#define CMD_ASR_N_CLASSES 11

static const char *const g_cmd_texts[CMD_ASR_N_CLASSES] = {
  "",
  "你好",
  "你是谁",
  "打开客厅的灯",
  "关闭客厅的灯",
  "现在几点了",
  "今天天气怎么样",
  "把空调调到26度",
  "播放音乐",
  "再见",
  "帮我发射火箭",
};

#endif
