/* Auto-generated by train_cmd_model.py - DO NOT EDIT */
#ifndef SPEECH_FEAT_STATS_H
#define SPEECH_FEAT_STATS_H

#define SPEECH_FEAT_MEAN -3.51735806e+00f
#define SPEECH_FEAT_INV_STD 2.80163129e-01f

#endif
