#!/usr/bin/env bash
# Generate the PAN debug board config from the product one.
#
# The debug config is generated rather than maintained by hand so it cannot
# drift from the product config: the whole point of Gate B is to trust that
# what the debug firmware captures is what the product firmware does, and a
# hand-edited copy silently diverges the first time the product defconfig
# changes.
#
# Adds the ACL trace plus the crash diagnostics the bring-up needs:
#   SF32LB52_BT_TRACE_ACL_FULL  - dump every HCI ACL packet, 32 bytes per
#                                 syslog line, which bnep_pcap.py turns back
#                                 into a pcap for Wireshark's BNEP dissector.
#   DEBUG_HARDFAULT_ALERT       - the CFSR/HFSR/DFSR/BFAR line and the real
#                                 faulting PC, which the PANIC_WITH_REGS dump
#                                 alone does not give (its PC/LR point at
#                                 _assert, not at the instruction that faulted).
#   DEBUG_BUSFAULT/USAGEFAULT   - same detail for the two faults that would
#                                 otherwise escalate into that hard fault.
#   ARCH_STACKDUMP              - stack contents behind the register dump.
#   BOARDCTL_RESET              - board_reset() already exists for this board
#                                 (sifli_ap.c -> up_systemreset), it was just
#                                 never compiled in.
#   BOARD_RESET_ON_ASSERT=2     - reboot on assert from *any* thread instead of
#                                 hanging with a dead console. Two reasons: the
#                                 crash log becomes repeatable, and each reboot
#                                 reopens the SFBL download window, so a crashed
#                                 board can be reflashed without the physical
#                                 USB replug that a silent hang forces.
#
# DEBUG_MEMFAULT is deliberately left off: it depends on ARCH_USE_MPU, and this
# is a flat build with no MPU regions, so turning the MPU on would change the
# memory behaviour the debug image is supposed to reproduce.
#
# None of these alter what the firmware does before it faults.
#
# It deliberately does NOT set CONFIG_BLUETOOTH_LOG, even though that is the
# symbol that defines CONFIG_BLUETOOTH_SERVICE_LOG_LEVEL and so unmutes the
# BT_LOG* macros in service/utils/log.h. Setting it also compiles
# service/utils/log_server.c, which calls property_monitor_close() from
# frameworks/system/utils/kvdb; CONFIG_KVDB is not set in this product config,
# so the link fails with an undefined reference. Enabling KVDB to get around
# that would add a server task and a storage backend the product firmware does
# not have, which defeats the purpose of the debug image - what it captures
# has to be what the product firmware actually does.
#
# Nothing is lost for PAN. Every line the bring-up needs already goes out over
# raw syslog in both builds: PAN_STATE_LOG in profiles/pan/panu_service.c and
# the syslog calls in stacks/zephyr/sal_pan_interface.c exist precisely
# because BT_LOG* is dead in the product config.
set -Eeuo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
BOARD_DIR="${BOARD_DIR:-$HERE/../../board/contest_board/configs}"
SRC="$BOARD_DIR/ai_agent/defconfig"
DST_DIR="$BOARD_DIR/ai_agent_pandbg"
DST="$DST_DIR/defconfig"

[[ -f "$SRC" ]] || { echo "product defconfig not found: $SRC" >&2; exit 1; }

mkdir -p "$DST_DIR"
{
  cat "$SRC"
  cat <<'EOF'

# ---------------------------------------------------------------------------
# Generated by docs_ble/tools/mk_pandbg_config.sh - do not edit by hand.
# Re-run the script after changing the product defconfig.
# ---------------------------------------------------------------------------
# Full-length HCI ACL trace: the capture source for Gate B. Very verbose
# (a 1691-byte PDU is ~53 syslog lines), so debug builds only.
CONFIG_SF32LB52_BT_TRACE_ACL_FULL=y

# Crash diagnostics. hfalert()/bfalert()/ufalert() in arm_hardfault.c and its
# siblings are no-ops without these, which is why the first bluetoothd crash
# only printed the _assert context and no fault status registers at all.
CONFIG_DEBUG_HARDFAULT_ALERT=y
CONFIG_DEBUG_BUSFAULT=y
CONFIG_DEBUG_USAGEFAULT=y
CONFIG_ARCH_STACKDUMP=y

# Reboot on assert rather than spinning in reset_board()'s LED loop with the
# console gone: >= 2 covers user threads, and every bluetoothd thread is one.
CONFIG_BOARDCTL_RESET=y
CONFIG_BOARD_RESET_ON_ASSERT=2
EOF
} > "$DST"

echo "wrote $DST"
echo "  base:  $(wc -l < "$SRC") lines from ai_agent/defconfig"
echo "  added: SF32LB52_BT_TRACE_ACL_FULL, DEBUG_HARDFAULT_ALERT,"
echo "         DEBUG_BUSFAULT, DEBUG_USAGEFAULT, ARCH_STACKDUMP,"
echo "         BOARDCTL_RESET, BOARD_RESET_ON_ASSERT=2"
echo
echo "Configure and build with:"
echo "  cd /home/aila/projects/vela_contest"
echo "  # build-tools is needed too: the romfs_etc.c rule shells out to bare"
echo "  # 'genromfs', which only lives in prebuilts/build-tools."
echo "  export PATH=\"\$PWD/prebuilts/gcc/linux-x86_64/arm-none-eabi/bin:\$PWD/prebuilts/build-tools/linux-x86_64/bin:\$PWD/prebuilts/kconfig-frontends/bin:\$PATH\""
echo "  prebuilts/tools/cmake/bin/cmake -B out/nuttx_contest_board_pandbg -GNinja \\"
echo "      -DBOARD_CONFIG=../contest2026_181_womenshayebuhuidui/board/contest_board/configs/ai_agent_pandbg \\"
echo "      -DEXTRA_FLAGS='-Wno-cpp -Wno-deprecated-declarations -Wno-error -Wno-strict-prototypes -Wno-undef' \\"
echo "      nuttx"
echo "  cd out/nuttx_contest_board_pandbg && ninja resetconfig && ninja -j8"
