#!/usr/bin/env python3
"""生成 velaAI 端侧模型在 ai_agent 中使用的 C 数据表。

产物 (写入 app/ai_agent/model/):
  model_data.h         - TFLite 模型字节数组 (RODATA, 16 字节对齐)
  tokenizer_v3_data.h  - SentencePiece 词表 (V3, vocab=5000):
                          piece 字节串 blob + 偏移/长度表 + FNV-1a 开放寻址哈希表

用法:
  python3 tools/gen_local_lm_tables.py \
      --tflite /path/to/mcu_language_model_v3_16x8.tflite \
      --sp-model /path/to/tokenizer_v3/tokenizer.model \
      --outdir model

依赖: sentencepiece (pip install sentencepiece)
"""
import argparse
import os
import sys

try:
    import sentencepiece as spm
except ImportError:
    sys.exit("缺少 sentencepiece: pip install sentencepiece")

SP_HASH_SIZE = 8192  # 5000 词条 -> 负载因子 0.61, 开放寻址
SP_HASH_EMPTY = 0xFFFF


def fnv1a(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def emit_c_array(f, name, data: bytes, per_line=12):
    f.write(f"alignas(16) const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        f.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    f.write("};\n")


def gen_model(outdir, tflite_path):
    data = open(tflite_path, "rb").read()
    print(f"[model] {tflite_path}: {len(data)} bytes")
    with open(os.path.join(outdir, "model_data.h"), "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by tools/gen_local_lm_tables.py - DO NOT EDIT */\n")
        f.write("#ifndef VELA_AI_MODEL_DATA_H\n#define VELA_AI_MODEL_DATA_H\n\n")
        f.write("#include <stddef.h>\n\n")
        emit_c_array(f, "g_velaai_model", data)
        f.write(f"\nconst size_t g_velaai_model_len = {len(data)};\n\n")
        f.write("#endif /* VELA_AI_MODEL_DATA_H */\n")
    print(f"[model] -> {os.path.join(outdir, 'model_data.h')}")


def gen_tokenizer(outdir, sp_path):
    sp = spm.SentencePieceProcessor()
    sp.load(sp_path)
    vocab = sp.vocab_size()
    pieces = [sp.id_to_piece(i).encode("utf-8") for i in range(vocab)]
    max_len = max(len(p) for p in pieces)

    blob = b"".join(pieces)
    off = [0] * (vocab + 1)
    acc = 0
    for i, p in enumerate(pieces):
        off[i] = acc
        acc += len(p)
    off[vocab] = acc
    assert acc == len(blob)

    # 哈希表: id 或 SP_HASH_EMPTY
    table = [SP_HASH_EMPTY] * SP_HASH_SIZE
    for i, p in enumerate(pieces):
        if i in (0, 1, 2):  # <pad>/<unk>/<eos> 也参与, 无妨
            pass
        h = fnv1a(p) & (SP_HASH_SIZE - 1)
        while table[h] != SP_HASH_EMPTY:
            h = (h + 1) & (SP_HASH_SIZE - 1)
        table[h] = i
    collisions = sum(1 for h in table if h != SP_HASH_EMPTY)
    assert collisions == vocab, f"hash 表冲突: {collisions} != {vocab}"

    print(f"[tokenizer] vocab={vocab} max_piece_len={max_len} blob={len(blob)} bytes")
    with open(os.path.join(outdir, "tokenizer_v3_data.h"), "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by tools/gen_local_lm_tables.py - DO NOT EDIT */\n")
        f.write("#ifndef VELA_AI_TOKENIZER_V3_DATA_H\n#define VELA_AI_TOKENIZER_V3_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define SP_VOCAB_SIZE {vocab}\n")
        f.write(f"#define SP_PAD_ID 0\n#define SP_UNK_ID 1\n#define SP_EOS_ID 2\n")
        f.write(f"#define SP_MAX_PIECE_LEN {max_len}\n")
        f.write(f"#define SP_HASH_SIZE {SP_HASH_SIZE}\n")
        f.write(f"#define SP_HASH_EMPTY {SP_HASH_EMPTY}\n\n")

        f.write(f"/* {len(blob)} bytes: 全部 piece UTF-8 字节串按 id 顺序拼接 */\n")
        f.write("static const uint8_t g_sp_piece_blob[] = {\n")
        for i in range(0, len(blob), 24):
            chunk = blob[i:i + 24]
            f.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n\n")

        f.write("/* 每个 piece 在 blob 中的起始偏移, 长度 = off[i+1]-off[i] */\n")
        f.write("static const uint32_t g_sp_piece_off[SP_VOCAB_SIZE + 1] = {\n")
        for i in range(0, vocab + 1, 12):
            f.write("  " + ", ".join(str(o) for o in off[i:i + 12]) + ",\n")
        f.write("};\n\n")

        f.write("/* FNV-1a 开放寻址哈希: piece 字节 -> id (SP_HASH_EMPTY=空槽) */\n")
        f.write("static const uint16_t g_sp_hash[SP_HASH_SIZE] = {\n")
        for i in range(0, SP_HASH_SIZE, 16):
            f.write("  " + ", ".join(str(t) for t in table[i:i + 16]) + ",\n")
        f.write("};\n\n")
        f.write("#endif /* VELA_AI_TOKENIZER_V3_DATA_H */\n")
    print(f"[tokenizer] -> {os.path.join(outdir, 'tokenizer_v3_data.h')}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tflite", required=True, help="TFLite 16x8 模型路径")
    ap.add_argument("--sp-model", required=True, help="SentencePiece model 路径")
    ap.add_argument("--outdir", default="model", help="输出目录")
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    gen_model(args.outdir, args.tflite)
    gen_tokenizer(args.outdir, args.sp_model)
    print("=== 生成完毕 ===")


if __name__ == "__main__":
    main()
