#!/usr/bin/env python3
"""Regenerate the launcher wallpaper as RGB565.

The asset was emitted as ARGB8888 (702,000 B of rodata) but every pixel has
alpha 0xff and the panel runs at CONFIG_LV_COLOR_DEPTH=16, so LVGL was
down-converting all 175,500 pixels on every redraw.  Storing RGB565 directly
halves the flash cost and drops that per-frame conversion.

Usage: python3 tools/gen_bg_rgb565.py <in.c> <out.c> [more_out.c ...]

Reads the ARGB8888 `img_background_watch_px` array from <in.c> and writes a
uint16_t RGB565 array of the same name to each output path.
"""
import re
import sys

W, H = 390, 450


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    src, outs = sys.argv[1], sys.argv[2:]

    text = open(src, encoding="utf-8").read()
    words = re.findall(r"0x([0-9a-fA-F]{8})", text)
    if len(words) != W * H:
        sys.exit("[gen] expected %d pixels, parsed %d" % (W * H, len(words)))

    out565 = []
    for w in words:
        v = int(w, 16)
        r = (v >> 16) & 0xFF
        g = (v >> 8) & 0xFF
        b = v & 0xFF
        out565.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))

    lines = [
        "#include <stdint.h>",
        "/* Generated by tools/gen_bg_rgb565.py from the ARGB8888 asset.",
        " * %dx%d RGB565, little endian; every source pixel had alpha 0xff." % (W, H),
        " */",
        "const uint16_t img_background_watch_px[%d] = {" % (W * H),
    ]
    for i in range(0, len(out565), 16):
        chunk = out565[i:i + 16]
        lines.append("    " + ", ".join("0x%04x" % p for p in chunk) + ",")
    lines.append("};")
    blob = "\n".join(lines) + "\n"

    for path in outs:
        open(path, "w", encoding="utf-8").write(blob)
        print("[gen] wrote %s (%d bytes source, %d bytes rodata)"
              % (path, len(blob), W * H * 2))


main()
